segments = ['economy', 'environment', 'family', 'balanced', 'joy']
segment_2_choice = {
    '1': 'Economy', 
    '2': 'Environment',
    '3': 'Family', 
    '4': 'Balanced',
    '5': 'Joy'
}


features = ['m', 'f', 's', 'p', 'r', 't', 'a', 'e', 'affordability']

population_distribution = {
    'economy_probability': 40,
    'economy_std': 5,
    'environment_probability': 5,
    'environment_std': 1,
    'family_probability': 25,
    'family_std': 2,
    'balanced_probability': 25,
    'balanced_std': 4,
    'joy_probability': 5,
    'joy_std': 1
}

segment_distribution = {
    'economy': {
        'maintenance_probability': 60,
        'fuel_cost_probability': 60,
        'safety_avg_value_probability': 20,
        'performance_avg_value_probability': 20,
        'range_avg_value_probability': 30,
        'tech_avg_value_probability': 15,
        'aesthetics_avg_value_probability': 40,
        'esg_friendly_avg_value_probability': 10,
        'cost_probability': 20000,

        'maintenance_std': 2,
        'fuel_cost_std': 2,
        'safety_avg_value_std': 5,
        'performance_avg_value_std': 5,
        'range_avg_value_std': 3,
        'tech_avg_value_std': 2,
        'aesthetics_avg_value_std': 5,
        'esg_friendly_avg_value_std': 3,
        'cost_std': 3000
    },
    'environment': {
        'maintenance_probability': 20,
        'fuel_cost_probability': 25,
        'safety_avg_value_probability': 35,
        'performance_avg_value_probability': 35,
        'range_avg_value_probability': 35,
        'tech_avg_value_probability': 50,
        'aesthetics_avg_value_probability': 40,
        'esg_friendly_avg_value_probability': 60,
        'cost_probability': 70000,
    
        'maintenance_std': 5,
        'fuel_cost_std': 5,
        'safety_avg_value_std': 2,
        'performance_avg_value_std': 5,
        'range_avg_value_std': 5,
        'tech_avg_value_std': 5,
        'aesthetics_avg_value_std': 10,
        'esg_friendly_avg_value_std': 10,
        'cost_std': 10000
    },
    'family': {
        'maintenance_probability': 30,
        'fuel_cost_probability': 35,
        'safety_avg_value_probability': 60,
        'performance_avg_value_probability': 40,
        'range_avg_value_probability': 50,
        'tech_avg_value_probability': 30,
        'aesthetics_avg_value_probability': 40,
        'esg_friendly_avg_value_probability': 40,
        'cost_probability': 50000,
        
        'maintenance_std': 5,
        'fuel_cost_std': 10,
        'safety_avg_value_std': 10,
        'performance_avg_value_std': 5,
        'range_avg_value_std': 10,
        'tech_avg_value_std': 10,
        'aesthetics_avg_value_std': 10,
        'esg_friendly_avg_value_std': 5,
        'cost_std': 5000
    },
    'balanced': {
        'maintenance_probability': 40,
        'fuel_cost_probability': 40,
        'safety_avg_value_probability': 35,
        'performance_avg_value_probability': 35,
        'range_avg_value_probability': 40,
        'tech_avg_value_probability': 25,
        'aesthetics_avg_value_probability': 35,
        'esg_friendly_avg_value_probability': 25,
        'cost_probability': 30000,
        
        'maintenance_std': 10,
        'fuel_cost_std': 10,
        'safety_avg_value_std': 5,
        'performance_avg_value_std': 5,
        'range_avg_value_std': 5,
        'tech_avg_value_std': 5,
        'aesthetics_avg_value_std': 5,
        'esg_friendly_avg_value_std': 5,
        'cost_std': 2000
    },
    'joy': {
        'maintenance_probability': 20,
        'fuel_cost_probability': 10,
        'safety_avg_value_probability': 10,
        'performance_avg_value_probability': 60,
        'range_avg_value_probability': 15,
        'tech_avg_value_probability': 40,
        'aesthetics_avg_value_probability': 60,
        'esg_friendly_avg_value_probability': 5,
        'cost_probability': 200000,
        
        'maintenance_std': 2,
        'fuel_cost_std': 2,
        'safety_avg_value_std': 5,
        'performance_avg_value_std': 10,
        'range_avg_value_std': 5,
        'tech_avg_value_std': 5,
        'aesthetics_avg_value_std': 15,
        'esg_friendly_avg_value_std': 1,
        'cost_std': 50000
    }   
}

shape_data = {
    'mini': {
        'cost_probability': 4000,
        'cost_std': 500,
        'maintenance_probability': 15,
        'maintenance_std': 1,
        'fuel_cost_probability': 15,
        'fuel_cost_std': 1,
        'safety_avg_value_probability': 2,
        'safety_avg_value_std': 1,
        'performance_avg_value_probability': 5,
        'performance_avg_value_std': 2,
        'range_avg_value_probability': 5,
        'range_avg_value_std': 1,
        'tech_avg_value_probability': 1,
        'tech_avg_value_std': 0.5,
        'aesthetics_avg_value_probability': 10,
        'aesthetics_avg_value_std': 1.0,
        'esg_friendly_avg_value_probability': 3,
        'esg_friendly_avg_value_std': 1
    },
    'modern': {
        'cost_probability': 12000,
        'cost_std': 2000,
        'maintenance_probability': 5,
        'maintenance_std': 3,
        'fuel_cost_probability': 10,
        'fuel_cost_std': 3,
        'safety_avg_value_probability': 10,
        'safety_avg_value_std': 3,
        'performance_avg_value_probability': 15,
        'performance_avg_value_std': 1,
        'range_avg_value_probability': 15,
        'range_avg_value_std': 1,
        'tech_avg_value_probability': 5,
        'tech_avg_value_std': 1.0,
        'aesthetics_avg_value_probability': 25,
        'aesthetics_avg_value_std': 5.0,
        'esg_friendly_avg_value_probability': 10,
        'esg_friendly_avg_value_std': 2
    },
    'suv': {
        'cost_probability': 15000,
        'cost_std': 1000,
        'maintenance_probability': 5,
        'maintenance_std': 1,
        'fuel_cost_probability': 8,
        'fuel_cost_std': 1,
        'safety_avg_value_probability': 15,
        'safety_avg_value_std': 1,
        'performance_avg_value_probability': 10,
        'performance_avg_value_std': 2,
        'range_avg_value_probability': 10,
        'range_avg_value_std': 2,
        'tech_avg_value_probability': 2,
        'tech_avg_value_std': 0.5,
        'aesthetics_avg_value_probability': 17,
        'aesthetics_avg_value_std': 0.5,
        'esg_friendly_avg_value_probability': 3,
        'esg_friendly_avg_value_std': 1
    },
    'sedan': {
        'cost_probability': 7000,
        'cost_std': 1000,
        'maintenance_probability': 12,
        'maintenance_std': 1,
        'fuel_cost_probability': 12,
        'fuel_cost_std': 1,
        'safety_avg_value_probability': 8,
        'safety_avg_value_std': 1,
        'performance_avg_value_probability': 10,
        'performance_avg_value_std': 7,
        'range_avg_value_probability': 10,
        'range_avg_value_std': 7,
        'tech_avg_value_probability': 2,
        'tech_avg_value_std': 0.5,
        'aesthetics_avg_value_probability': 15,
        'aesthetics_avg_value_std': 0.5,
        'esg_friendly_avg_value_probability': 3,
        'esg_friendly_avg_value_std': 1
    },
    'sports': {
        'cost_probability': 25000,
        'cost_std': 2000,
        'maintenance_probability': 1,
        'maintenance_std': 1,
        'fuel_cost_probability': 1,
        'fuel_cost_std': 1,
        'safety_avg_value_probability': 3,
        'safety_avg_value_std': 1,
        'performance_avg_value_probability': 20,
        'performance_avg_value_std': 7,
        'range_avg_value_probability': 5,
        'range_avg_value_std': 7,
        'tech_avg_value_probability': 4,
        'tech_avg_value_std': 0.5,
        'aesthetics_avg_value_probability': 30,
        'aesthetics_avg_value_std': 0.5,
        'esg_friendly_avg_value_probability': 0.1,
        'esg_friendly_avg_value_std': 1
  }
}

engine_data = { 
    'diesel_engine': {
        'cost_probability': 4000,
        'cost_std': 200,
        'maintenance_probability': 5,
        'maintenance_std': 2,
        'fuel_cost_probability': 10,
        'fuel_cost_std': 1,
        'safety_avg_value_probability': 5,
        'safety_avg_value_std': 1.0,
        'performance_avg_value_probability': 15,
        'performance_avg_value_std': 1,
        'range_avg_value_probability': 15,
        'range_avg_value_std': 1,
        'tech_avg_value_probability': 5,
        'tech_avg_value_std': 1,
        'aesthetics_avg_value_probability': 0.1,
        'aesthetics_avg_value_std': 0.5,
        'esg_friendly_avg_value_probability': -10,
        'esg_friendly_avg_value_std': 1
    },
    'hybrid_engine': {
        'cost_probability': 6000,
        'cost_std': 500,
        'maintenance_probability': 10,
        'maintenance_std': 3,
        'fuel_cost_probability': 15,
        'fuel_cost_std': 3,
        'safety_avg_value_probability': 5,
        'safety_avg_value_std': 1.5,
        'performance_avg_value_probability': 10,
        'performance_avg_value_std': 2,
        'range_avg_value_probability': 20,
        'range_avg_value_std': 2,
        'tech_avg_value_probability': 7,
        'tech_avg_value_std': 2,
        'aesthetics_avg_value_probability': 0.1,
        'aesthetics_avg_value_std': 0.5,
        'esg_friendly_avg_value_probability': 5,
        'esg_friendly_avg_value_std': 1
    },
    'electric_engine': {
        'cost_probability': 10000,
        'cost_std': 4000,
        'maintenance_probability': 15,
        'maintenance_std': 10,
        'fuel_cost_probability': 25,
        'fuel_cost_std': 5,
        'safety_avg_value_probability': 10,
        'safety_avg_value_std': 3.0,
        'performance_avg_value_probability': 25,
        'performance_avg_value_std': 7,
        'range_avg_value_probability': 8,
        'range_avg_value_std': 7,
        'tech_avg_value_probability': 15,
        'tech_avg_value_std': 3,
        'aesthetics_avg_value_probability': 0.1,
        'aesthetics_avg_value_std': 1.0,
        'esg_friendly_avg_value_probability': 20,
        'esg_friendly_avg_value_std': 5
    }
}

steel_data = {
    'aerodynamic': {
        'cost_probability': 10000,
        'cost_std': 2000,
        'maintenance_probability': 3,
        'maintenance_std': 2,
        'fuel_cost_probability': 10,
        'fuel_cost_std': 2,
        'safety_avg_value_probability': 6,
        'safety_avg_value_std': 1.0,
        'performance_avg_value_probability': 5,
        'performance_avg_value_std': 2.0,
        'range_avg_value_probability': 10,
        'range_avg_value_std': 1.0,
        'tech_avg_value_probability': 2,
        'tech_avg_value_std': 1.0,
        'aesthetics_avg_value_probability': 5,
        'aesthetics_avg_value_std': 1.0,
        'esg_friendly_avg_value_probability': 5,
        'esg_friendly_avg_value_std': 1.0
    },
    'paper_thin': {
        'cost_probability': 3000,
        'cost_std': 600,
        'maintenance_probability': -5,
        'maintenance_std': 2,
        'fuel_cost_probability': 0.1,
        'fuel_cost_std': 2,
        'safety_avg_value_probability': -3,
        'safety_avg_value_std': 2.0,
        'performance_avg_value_probability': 0.1,
        'performance_avg_value_std': 0.1,
        'range_avg_value_probability': 2,
        'range_avg_value_std': 2.0,
        'tech_avg_value_probability': -1,
        'tech_avg_value_std': 0.5,
        'aesthetics_avg_value_probability': -5,
        'aesthetics_avg_value_std': 0.5,
        'esg_friendly_avg_value_probability': -1,
        'esg_friendly_avg_value_std': 0.5
    },
    'built_like_tank': {
        'cost_probability': 7500,
        'cost_std': 1000,
        'maintenance_probability': 8,
        'maintenance_std': 3,
        'fuel_cost_probability': -5,
        'fuel_cost_std': 3,
        'safety_avg_value_probability': 8,
        'safety_avg_value_std': 1.0,
        'performance_avg_value_probability': -5,
        'performance_avg_value_std': 1.0,
        'range_avg_value_probability': -8,
        'range_avg_value_std': 1.0,
        'tech_avg_value_probability': -1,
        'tech_avg_value_std': 0.5,
        'aesthetics_avg_value_probability': -2,
        'aesthetics_avg_value_std': 0.5,
        'esg_friendly_avg_value_probability': -2,
        'esg_friendly_avg_value_std': 0.5
    },
    'generic_steel': {
        'cost_probability': 5000,
        'cost_std': 1000,
        'maintenance_probability': 5,
        'maintenance_std': 1,
        'fuel_cost_probability': 0.1,
        'fuel_cost_std': 1,
        'safety_avg_value_probability': 3,
        'safety_avg_value_std': 0.5,
        'performance_avg_value_probability': 0.1,
        'performance_avg_value_std': 0.5,
        'range_avg_value_probability': 0.1,
        'range_avg_value_std': 0.5,
        'tech_avg_value_probability': -1,
        'tech_avg_value_std': 0.5,
        'aesthetics_avg_value_probability': 1,
        'aesthetics_avg_value_std': 0.5,
        'esg_friendly_avg_value_probability': -1,
        'esg_friendly_avg_value_std': 0.5
    }
}

glass_data = { 
    'aerodynamic': {
        'cost_probability': 1000,
        'cost_std': 200,
        'maintenance_probability': 3,
        'maintenance_std': 1,
        'fuel_cost_probability': 5,
        'fuel_cost_std': 1.0,
        'safety_avg_value_probability': 5,
        'safety_avg_value_std': 1,
        'performance_avg_value_probability': 3,
        'performance_avg_value_std': 1,
        'range_avg_value_probability': 3,
        'range_avg_value_std': 1,
        'tech_avg_value_probability': 2,
        'tech_avg_value_std': 1,
        'aesthetics_avg_value_probability': 3,
        'aesthetics_avg_value_std': 0.3,
        'esg_friendly_avg_value_probability': 5,
        'esg_friendly_avg_value_std': 1.0
    },
    'lean': {
        'cost_probability': 300,
        'cost_std': 50,
        'maintenance_probability': -3,
        'maintenance_std': 3,
        'fuel_cost_probability': 0.1,
        'fuel_cost_std': 0.1,
        'safety_avg_value_probability': -10,
        'safety_avg_value_std': 3,
        'performance_avg_value_probability': 0.1,
        'performance_avg_value_std': 0.1,
        'range_avg_value_probability': 0.1,
        'range_avg_value_std': 3,
        'tech_avg_value_probability': -1,
        'tech_avg_value_std': 3,
        'aesthetics_avg_value_probability': 0.1,
        'aesthetics_avg_value_std': 3.0,
        'esg_friendly_avg_value_probability': -1,
        'esg_friendly_avg_value_std': 0.5
    },
    'gorilla_glass': {
        'cost_probability': 600,
        'cost_std': 100,
        'maintenance_probability': 6,
        'maintenance_std': 1,
        'fuel_cost_probability': -1,
        'fuel_cost_std': 0.5,
        'safety_avg_value_probability': 5,
        'safety_avg_value_std': 1,
        'performance_avg_value_probability': 1,
        'performance_avg_value_std': 1,
        'range_avg_value_probability': -2,
        'range_avg_value_std': 1,
        'tech_avg_value_probability': 2,
        'tech_avg_value_std': 1,
        'aesthetics_avg_value_probability': 2,
        'aesthetics_avg_value_std': 0.3,
        'esg_friendly_avg_value_probability': -2,
        'esg_friendly_avg_value_std': 0.5
    },
    'generic_glass': {
        'cost_probability': 550,
        'cost_std': 20,
        'maintenance_probability': 1,
        'maintenance_std': 1,
        'fuel_cost_probability': 0.1,
        'fuel_cost_std': 0.1,
        'safety_avg_value_probability': 0.1,
        'safety_avg_value_std': 1,
        'performance_avg_value_probability': 1,
        'performance_avg_value_std': 1,
        'range_avg_value_probability': 0.1,
        'range_avg_value_std': 1,
        'tech_avg_value_probability': 0.1,
        'tech_avg_value_std': 1,
        'aesthetics_avg_value_probability': 0.1,
        'aesthetics_avg_value_std': 0.3,
        'esg_friendly_avg_value_probability': -1,
        'esg_friendly_avg_value_std': 0.5
    }
}

lights_data = {
    'led': {
        'cost_probability': 2000,
        'cost_std': 200,
        'maintenance_probability': 3,
        'maintenance_std': 1,
        'fuel_cost_probability': 0.1,
        'fuel_cost_std': 0.1,
        'safety_avg_value_probability': 5,
        'safety_avg_value_std': 0.1,
        'performance_avg_value_probability': 1,
        'performance_avg_value_std': 0.1,
        'range_avg_value_probability': 4,
        'range_avg_value_std': 0.1,
        'tech_avg_value_probability': 3,
        'tech_avg_value_std': 1.0,
        'aesthetics_avg_value_probability': 5,
        'aesthetics_avg_value_std': 1.0,
        'esg_friendly_avg_value_probability': 5,
        'esg_friendly_avg_value_std': 1.0
    },
    'frosty': {
        'cost_probability': 600,
        'cost_std': 50,
        'maintenance_probability': -3,
        'maintenance_std': 2,
        'fuel_cost_probability': 0.1,
        'fuel_cost_std': 0.1,
        'safety_avg_value_probability': -5,
        'safety_avg_value_std': 1,
        'performance_avg_value_probability': 0.1,
        'performance_avg_value_std': 0.1,
        'range_avg_value_probability': -5,
        'range_avg_value_std': 0.1,
        'tech_avg_value_probability': -1,
        'tech_avg_value_std': 0.5,
        'aesthetics_avg_value_probability': -2,
        'aesthetics_avg_value_std': 0.5,
        'esg_friendly_avg_value_probability': -1,
        'esg_friendly_avg_value_std': 0.5
    },
    'halogen': {
        'cost_probability': 1200,
        'cost_std': 100,
        'maintenance_probability': -1,
        'maintenance_std': 1,
        'fuel_cost_probability': 0.1,
        'fuel_cost_std': 0.1,
        'safety_avg_value_probability': 5,
        'safety_avg_value_std': 0.1,
        'performance_avg_value_probability': 0.1,
        'performance_avg_value_std': 0.1,
        'range_avg_value_probability': -5,
        'range_avg_value_std': 0.1,
        'tech_avg_value_probability': 1,
        'tech_avg_value_std': 0.5,
        'aesthetics_avg_value_probability': 2,
        'aesthetics_avg_value_std': 0.5,
        'esg_friendly_avg_value_probability': -2,
        'esg_friendly_avg_value_std': 0.5
    },
    'generic_lights': {
        'cost_probability': 800,
        'cost_std': 100,
        'maintenance_probability': 1,
        'maintenance_std': 1,
        'fuel_cost_probability': 0.1,
        'fuel_cost_std': 0.1,
        'safety_avg_value_probability': 0.1,
        'safety_avg_value_std': 0.1,
        'performance_avg_value_probability': 0.1,
        'performance_avg_value_std': 0.1,
        'range_avg_value_probability': -2,
        'range_avg_value_std': 0.1,
        'tech_avg_value_probability': 0.1,
        'tech_avg_value_std': 0.5,
        'aesthetics_avg_value_probability': 1,
        'aesthetics_avg_value_std': 0.1,
        'esg_friendly_avg_value_probability': -1,
        'esg_friendly_avg_value_std': 0.5
    }
}

tyres_data = {
    'precision': {
        'cost_probability': 3000,
        'cost_std': 300,
        'maintenance_probability': 3,
        'maintenance_std': 2.0,
        'fuel_cost_probability': 2,
        'fuel_cost_std': 0.5,
        'safety_avg_value_probability': 5,
        'safety_avg_value_std': 0.5,
        'performance_avg_value_probability': 4,
        'performance_avg_value_std': 0.5,
        'range_avg_value_probability': 3,
        'range_avg_value_std': 0.5,
        'tech_avg_value_probability': 3,
        'tech_avg_value_std': 1.0,
        'aesthetics_avg_value_probability': 5,
        'aesthetics_avg_value_std': 1.0,
        'esg_friendly_avg_value_probability': 5,
        'esg_friendly_avg_value_std': 1.0
    },
    'economy': {
        'cost_probability': 1000,
        'cost_std': 200,
        'maintenance_probability': -3,
        'maintenance_std': 1.0,
        'fuel_cost_probability': -1,
        'fuel_cost_std': 1.0,
        'safety_avg_value_probability': -2,
        'safety_avg_value_std': 1.0,
        'performance_avg_value_probability': -3,
        'performance_avg_value_std': 1.0,
        'range_avg_value_probability': -1,
        'range_avg_value_std': 1.0,
        'tech_avg_value_probability': -1,
        'tech_avg_value_std': 0.5,
        'aesthetics_avg_value_probability': -2,
        'aesthetics_avg_value_std': 1.0,
        'esg_friendly_avg_value_probability': -1,
        'esg_friendly_avg_value_std': 0.5
    },
    'grippy': {
        'cost_probability': 1200,
        'cost_std': 100,
        'maintenance_probability': 5,
        'maintenance_std': 0.5,
        'fuel_cost_probability': -5,
        'fuel_cost_std': 0.5,
        'safety_avg_value_probability': 5,
        'safety_avg_value_std': 0.5,
        'performance_avg_value_probability': 3,
        'performance_avg_value_std': 0.5,
        'range_avg_value_probability': -3,
        'range_avg_value_std': 0.5,
        'tech_avg_value_probability': 1,
        'tech_avg_value_std': 0.5,
        'aesthetics_avg_value_probability': 2,
        'aesthetics_avg_value_std': 0.5,
        'esg_friendly_avg_value_probability': -2,
        'esg_friendly_avg_value_std': 0.5
    },
    'generic_tyre': {
        'cost_probability': 1100,
        'cost_std': 100,
        'maintenance_probability': -1,
        'maintenance_std': 0.5,
        'fuel_cost_probability': 0.1,
        'fuel_cost_std': 0.1,
        'safety_avg_value_probability': 0.1,
        'safety_avg_value_std': 0.5,
        'performance_avg_value_probability': -1,
        'performance_avg_value_std': 0.5,
        'range_avg_value_probability': 0.1,
        'range_avg_value_std': 0.5,
        'tech_avg_value_probability': 0.1,
        'tech_avg_value_std': 0.5,
        'aesthetics_avg_value_probability': 0.1,
        'aesthetics_avg_value_std': 0.5,
        'esg_friendly_avg_value_probability': -1,
        'esg_friendly_avg_value_std': 0.5
    }
}

plastic_data = { 
    'bio_plastic': {
        'cost_probability': 5000,
        'cost_std': 1000,
        'maintenance_probability': 4,
        'maintenance_std': 2.0,
        'fuel_cost_probability': 0.1,
        'fuel_cost_std': 0.1,
        'safety_avg_value_probability': -3,
        'safety_avg_value_std': 0.5,
        'performance_avg_value_probability': 0.1,
        'performance_avg_value_std': 0.5,
        'range_avg_value_probability': 0.1,
        'range_avg_value_std': 0.5,
        'tech_avg_value_probability': 3,
        'tech_avg_value_std': 1.0,
        'aesthetics_avg_value_probability': 10,
        'aesthetics_avg_value_std': 1.0,
        'esg_friendly_avg_value_probability': 5,
        'esg_friendly_avg_value_std': 1.0
    },
    'rough_plastic': {
        'cost_probability': 1500,
        'cost_std': 200,
        'maintenance_probability': -2,
        'maintenance_std': 1.0,
        'fuel_cost_probability': 0.1,
        'fuel_cost_std': 0.1,
        'safety_avg_value_probability': -2,
        'safety_avg_value_std': 0.5,
        'performance_avg_value_probability': 0.1,
        'performance_avg_value_std': 0.5,
        'range_avg_value_probability': 0.1,
        'range_avg_value_std': 0.5,
        'tech_avg_value_probability': -1,
        'tech_avg_value_std': 0.5,
        'aesthetics_avg_value_probability': -5,
        'aesthetics_avg_value_std': 0.5,
        'esg_friendly_avg_value_probability': -1,
        'esg_friendly_avg_value_std': 0.5
    },
    'luxury_plastic': {
        'cost_probability': 3500,
        'cost_std': 300,
        'maintenance_probability': 3,
        'maintenance_std': 0.5,
        'fuel_cost_probability': 0.1,
        'fuel_cost_std': 0.1,
        'safety_avg_value_probability': 3,
        'safety_avg_value_std': 0.5,
        'performance_avg_value_probability': 0.1,
        'performance_avg_value_std': 0.5,
        'range_avg_value_probability': 0.1,
        'range_avg_value_std': 0.5,
        'tech_avg_value_probability': 1,
        'tech_avg_value_std': 0.5,
        'aesthetics_avg_value_probability': 7,
        'aesthetics_avg_value_std': 0.5,
        'esg_friendly_avg_value_probability': -2,
        'esg_friendly_avg_value_std': 0.5
    },
    'generic': {
        'cost_probability': 2500,
        'cost_std': 100,
        'maintenance_probability': 0.1,
        'maintenance_std': 0.5,
        'fuel_cost_probability': 0.1,
        'fuel_cost_std': 0.1,
        'safety_avg_value_probability': 1,
        'safety_avg_value_std': 0.5,
        'performance_avg_value_probability': 0.1,
        'performance_avg_value_std': 0.5,
        'range_avg_value_probability': 0.1,
        'range_avg_value_std': 0.5,
        'tech_avg_value_probability': 0.1,
        'tech_avg_value_std': 0.5,
        'aesthetics_avg_value_probability': 3,
        'aesthetics_avg_value_std': 0.5,
        'esg_friendly_avg_value_probability': -1,
        'esg_friendly_avg_value_std': 0.5
    }
}

competitors = {
    'competitor_economy1': {
        'm': 19, 
        'f': 24,
        's': 10,
        'p': 15, 
        'r': 12, 
        't': 0, 
        'a': 1, 
        'e': -11, 
        'cost': 15907
    },

    'competitor_env1': {
        'm': 16, 
        'f': 33,
        's': 15,
        'p': 44, 
        'r': 16, 
        't': 21, 
        'a': 35, 
        'e': 36, 
        'cost': 36281
    },
    
    'competitor_fam1': {
        'm': 30, 
        'f': 14,
        's': 20,
        'p': 27, 
        'r': 19, 
        't': 11, 
        'a': 31, 
        'e': -3, 
        'cost': 33179
    },

    'competitor_balanced1': {
        'm': 20, 
        'f': 41,
        's': 15,
        'p': 29, 
        'r': 37, 
        't': 12, 
        'a': 23, 
        'e': 15, 
        'cost': 28687
    },

    'competitor_joy1': {
        'm': 120, 
        'f': 100,
        's': 140,
        'p': 160, 
        'r': 90, 
        't': 150, 
        'a': 115, 
        'e': 200, 
        'cost': 47077
    },
    

     'competitor_joy2': {
        'm': 40, 
        'f': 70,
        's': 60,
        'p': 80, 
        'r': 26, 
        't': 40, 
        'a': 94, 
        'e': 10, 
        'cost': 47077
    },
     'competitor_joy3': {
        'm': 39, 
        'f': 90,
        's': 50,
        'p': 47, 
        'r': 92, 
        't': 72, 
        'a': 49, 
        'e': 1, 
        'cost': 47077
    }
}

